# Run tests
#
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: API tests

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (and submodules)
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Reference: https://github.com/actions/cache/blob/main/examples.md#python---pip
      - uses: actions/cache@v2
        with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

      - name: Install package (and dependencies)
        run: pip install -e .

      # TODO: Run tests
